import http from "node:http";

const port = Number(process.env.PORT || 8787);
const apiKey = process.env.TYPESAFE_API_KEY;
if (!apiKey) throw new Error("Set TYPESAFE_API_KEY before starting the classifier backend.");

function json(response, status, payload) { response.writeHead(status, { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" }); response.end(JSON.stringify(payload)); }
function body(request) { return new Promise((resolve, reject) => { let value = ""; request.on("data", (chunk) => { value += chunk; if (value.length > 150000) reject(new Error("Request too large")); }); request.on("end", () => { try { resolve(JSON.parse(value)); } catch { reject(new Error("Invalid JSON")); } }); request.on("error", reject); }); }
function questions() { return { adequateEvidence: { type: "choice", instructions: "Is the job description detailed enough to judge fit and work authorization?", criteria: { yes: "It has substantive responsibilities or requirements.", no: "It is incomplete or generic." } }, roleFit: { type: "score", instructions: "Rate fit to the candidate target roles.", criteria: ["Incompatible", "Weak", "Partial", "Good", "Strong"] }, skillsFit: { type: "score", instructions: "Rate overlap between job requirements and candidate skills.", criteria: ["None", "Limited", "Partial", "Strong", "Direct strong"] }, experienceFit: { type: "score", instructions: "Rate compatibility with candidate experience.", criteria: ["Incompatible", "Weak", "Partial", "Good", "Strong"] }, sponsorship: { type: "choice", instructions: "Classify sponsorship language. Do not infer no future sponsorship from a generic current-work-authorization requirement alone.", criteria: { available: "Explicitly available", unavailable: "Explicitly unavailable", not_stated: "No policy stated after adequate review", ambiguous: "Conditional, conflicting, or unclear" } } }; }
async function classify(input) { if (!input?.job?.description || !input.profile) throw new Error("A full job description and profile are required."); const state = JSON.stringify({ candidate: { targetRoles: input.profile.targetRoles || [], skills: input.profile.skills || [], yearsExperience: input.profile.yearsExperience ?? null, needsSponsorship: Boolean(input.profile.needsSponsorship) }, job: { title: input.job.title, company: input.job.company, location: input.job.location, description: input.job.description } }); const remote = await fetch("https://api.typesafe.ai/v1/systemone", { method: "POST", headers: { Authorization: "Bearer " + apiKey, "Content-Type": "application/json" }, body: JSON.stringify({ model: "jev-latest", state, questions: questions() }) }); if (!remote.ok) throw new Error("TypeSafe API returned " + remote.status); const payload = await remote.json(); const a = payload.answers; const confidence = Math.min(a.roleFit.confidence, a.skillsFit.confidence, a.experienceFit.confidence, a.sponsorship.confidence); const fit = 10 * (0.4 * a.roleFit.score + 0.35 * a.skillsFit.score + 0.25 * a.experienceFit.score) / 4; return { adequateEvidence: a.adequateEvidence.choice === "yes", sponsorship: a.sponsorship.choice, fit: Math.round(fit * 10) / 10, confidence, model: payload.model, usage: payload.usage }; }
http.createServer(async (request, response) => { if (request.method === "OPTIONS") return json(response, 204, {}); if (request.method !== "POST" || request.url !== "/v1/classify") return json(response, 404, { error: "Not found" }); try { json(response, 200, await classify(await body(request))); } catch (error) { json(response, 400, { error: error.message }); } }).listen(port, "127.0.0.1", () => console.log("Job Sieve backend listening on http://127.0.0.1:" + port));
