import { mkdir, readFile, writeFile } from "node:fs/promises";

const files = [
  "src/shared/contracts.js",
  "src/content/adapters.js",
  "src/content/policy.js",
  "src/content/content-script.js"
];

let bundle = "/* Generated by scripts/build-content.mjs. Do not edit directly. */\n";
for (const file of files) {
  let source = await readFile(file, "utf8");
  source = source.replace(/^import .*?;\n/gm, "");
  source = source.replace(/export const /g, "const ");
  source = source.replace(/export function /g, "function ");
  bundle += "\n/* " + file + " */\n" + source;
}
await mkdir("dist", { recursive: true });
await writeFile("dist/content-script.js", bundle);
